<sl-menu-label>Legjobb emelet</sl-menu-label>
<sl-menu-item value="roomid_66.in">1/1</sl-menu-item>
<sl-menu-item value="roomid_67.in">1/2</sl-menu-item>
<sl-menu-item value="roomid_68.in">1/3</sl-menu-item>
<sl-menu-item value="roomid_69.in">1/4</sl-menu-item>
<sl-menu-item value="roomid_70.in">1/5</sl-menu-item>
<sl-menu-item value="roomid_71.in">1/6</sl-menu-item>
<sl-menu-item value="roomid_72.in">1/7</sl-menu-item>
<sl-menu-item value="roomid_73.in">1/8</sl-menu-item>
<sl-menu-item value="roomid_74.in">1/9</sl-menu-item>
<sl-menu-item value="roomid_127.in">1/9¾</sl-menu-item>
<sl-menu-item value="roomid_75.in">1/10</sl-menu-item>
<sl-menu-item value="roomid_128.in">1/vendég</sl-menu-item>
<sl-divider />
<sl-menu-label>Második emelet</sl-menu-label>
<sl-menu-item value="roomid_76.in">2/11</sl-menu-item>
<sl-menu-item value="roomid_77.in">2/12</sl-menu-item>
<sl-menu-item value="roomid_78.in">2/13</sl-menu-item>
<sl-menu-item value="roomid_79.in">2/14</sl-menu-item>
<sl-menu-item value="roomid_80.in">2/15</sl-menu-item>
<sl-menu-item value="roomid_81.in">2/16</sl-menu-item>
<sl-menu-item value="roomid_82.in">2/17</sl-menu-item>
<sl-menu-item value="roomid_83.in">2/18</sl-menu-item>
<sl-menu-item value="roomid_84.in">2/19</sl-menu-item>
<sl-menu-item value="roomid_85.in">2/20</sl-menu-item>
<sl-menu-item value="roomid_129.in">2/senior</sl-menu-item>
<sl-divider />
<sl-menu-label>Harmadik emelet</sl-menu-label>
<sl-menu-item value="roomid_86.in">3/21</sl-menu-item>
<sl-menu-item value="roomid_87.in">3/22</sl-menu-item>
<sl-menu-item value="roomid_88.in">3/23</sl-menu-item>
<sl-menu-item value="roomid_89.in">3/24</sl-menu-item>
<sl-menu-item value="roomid_90.in">3/25</sl-menu-item>
<sl-menu-item value="roomid_91.in">3/26</sl-menu-item>
<sl-menu-item value="roomid_92.in">3/27</sl-menu-item>
<sl-menu-item value="roomid_93.in">3/28</sl-menu-item>
<sl-menu-item value="roomid_94.in">3/29</sl-menu-item>
<sl-menu-item value="roomid_95.in">3/30</sl-menu-item>
<sl-menu-item value="roomid_130.in">3/senior</sl-menu-item>
<sl-menu-item value="roomid_131.in">3/vasaló</sl-menu-item>
<sl-divider />
<sl-menu-label>Negyedik emelet</sl-menu-label>
<sl-menu-item value="roomid_96.in">4/31</sl-menu-item>
<sl-menu-item value="roomid_97.in">4/32</sl-menu-item>
<sl-menu-item value="roomid_98.in">4/33</sl-menu-item>
<sl-menu-item value="roomid_99.in">4/34</sl-menu-item>
<sl-menu-item value="roomid_135.in">4/35</sl-menu-item>
<sl-menu-item value="roomid_101.in">4/36</sl-menu-item>
<sl-menu-item value="roomid_102.in">4/37</sl-menu-item>
<sl-menu-item value="roomid_103.in">4/38</sl-menu-item>
<sl-menu-item value="roomid_104.in">4/39</sl-menu-item>
<sl-menu-item value="roomid_105.in">4/40</sl-menu-item>
<sl-menu-item value="roomid_132.in">4/42</sl-menu-item>
<sl-menu-item value="roomid_133.in">4/43</sl-menu-item>
<sl-menu-item value="roomid_134.in">4/senior</sl-menu-item>
<sl-divider />
<sl-menu-label>Ötödik emelet</sl-menu-label>
<sl-menu-item value="roomid_106.in">V/1</sl-menu-item>
<sl-menu-item value="roomid_107.in">V/2</sl-menu-item>
<sl-menu-item value="roomid_108.in">V/3</sl-menu-item>
<sl-menu-item value="roomid_109.in">V/4</sl-menu-item>
<sl-menu-item value="roomid_110.in">V/5</sl-menu-item>
<sl-menu-item value="roomid_111.in">V/6</sl-menu-item>
<sl-menu-item value="roomid_112.in">V/7</sl-menu-item>
<sl-menu-item value="roomid_113.in">V/8</sl-menu-item>
<sl-menu-item value="roomid_114.in">V/9</sl-menu-item>
<sl-menu-item value="roomid_115.in">V/10</sl-menu-item>
<sl-menu-item value="roomid_116.in">V/11</sl-menu-item>
<sl-menu-item value="roomid_117.in">V/12</sl-menu-item>
<sl-menu-item value="roomid_118.in">V/13</sl-menu-item>
<sl-menu-item value="roomid_119.in">V/14</sl-menu-item>
<sl-menu-item value="roomid_120.in">V/15</sl-menu-item>
<sl-menu-item value="roomid_121.in">V/16</sl-menu-item>
<sl-menu-item value="roomid_122.in">V/17</sl-menu-item>
<sl-menu-item value="roomid_123.in">V/18</sl-menu-item>
<sl-menu-item value="roomid_124.in">V/19</sl-menu-item>
<sl-menu-item value="roomid_125.in">V/20</sl-menu-item>
<sl-menu-item value="roomid_126.in">V/21</sl-menu-item>
